---
title: "Exercise 6"
author: "Cameron Bale"
format: docx
---

1. Do a check-in. What worked well for you in this past unit? What didn't go well? If you have any questions or need support, reach out to a TA or the instructor (you are not graded on this part!)
2. Have you stayed organized? If not, go back and organize the material from Unit 1. Recommit yourself to keeping files organized on your computer for Unit 2. (again - not graded on this, it's for your benefit!)
3. Read 'Case-02-Nielsen-Sales.pdf' document that is posted on Canvas (it is located in the same subsection as this lecture). Write a response about how you might analyze the data to address the client's needs (no more than a page). Submit your response as a Word document on Canvas.

**Five points total:**

- **Four points for writing about meeting case expectations.**
- **One point for submitting a rendered Word document.**

## Meeting Expectations

To model how promotions and promotional spending are driving sales for various trade areas, sub-categories, and brands we'll first need to identify what combination of those variables we need to filter observations by so we can run a series of models. By running overall and specific models we can target recommendations to each subset of the data and contrast with the effects of promotions across the category.

In terms of the variables we might include, we'll need to get a data dictionary to understand what all of the constructed variables represent, but the outcome is likely `Sales` or `Base_Sales` for each model. Furthermore, we'll have to determine which of the promotional variables and other variables related to sales should be included.

